-- name: catch_all_form
-- Get catch all observations
select row_to_json(t) from (
    select id,
        study as "Étude",
        protocol as "Procédure",
        observation_period,
        observation_period_beginning as observation_date,
        observation_period_beginning as "Début d'observation",
        observation_period_ending as "Fin d'observation",
        observers,
        observer_names,
        data_source,
        data_source_title as "Type de source",
        ref_source as "Source",
        data_type ,
        data_type_title as "Publique",
        presence,
        presence_title as "Présence",
        subject_type,
        subject_type_title as "Objet dnbr",
        taxon,
        taxon_name as subject,
        quoted_name as "Nom cité",
        observation_method,
        observation_method_title as "Méthode obs",
        count_range,
        count_min as "Effectif min",
        count_max as "Effectif max",
        count_method,
        count_method_title as "Méthode dnbr",
        living_status,
        living_status_title as "Vivant",
        domestication_status,
        domestication_status_title as "Naturalité",
        gender,
        gender_title as "Sexe",
        age,
        age_title as "Stade",
        biogeographical_status,
        biogeographical_status_title as "Statut biogéo",
        biological_status,
        biological_status_title as "Statut biol",
        bird_breeding_code,
        bird_breeding_code_title as "Ind nidification",
        altitude_range,
        altitude_min as "Altitude min",
        altitude_max as "Altitude max",
        deep_range,
        deep_min as "Profondeur min",
        deep_max as "Profondeur max",
        evidence,
        evidence_title,
        evidence_url as "URL preuve",
        comments as "Commentaires",
        geometry,
        wfs_geometry,
        dc_title,
        dc_date_created,
        dc_date_modified,
        dc_date_submitted,
        dc_date_accepted,
        dc_date_issued,
        dc_creator,
        validator,
        dc_publisher,
        dc_language,
        dc_type
      from no_protocol.catch_all_view
      order by dc_date_modified desc
  ) as t;
  
